// --- Data Mock ---
// Images are now local files generated by AI
const PRODUCTS = [
    {
        id: 1,
        name: 'Beras Pandan Wangi 5kg',
        price: 65000,
        category: 'Sembako',
        image: 'C:/Users/Admin/.gemini/antigravity/brain/67d00d68-10c7-45d5-82df-78b5ae92d38b/product_rice_1764037916766.png',
        desc: 'Beras putih berkualitas premium dengan aroma pandan wangi alami. Pulen dan bersih, cocok untuk hidangan keluarga sehari-hari.'
    },
    {
        id: 2,
        name: 'Minyak Goreng 2L',
        price: 32000,
        category: 'Sembako',
        image: 'C:/Users/Admin/.gemini/antigravity/brain/67d00d68-10c7-45d5-82df-78b5ae92d38b/product_oil_1764037943879.png',
        desc: 'Minyak goreng kelapa sawit pilihan, jernih dan tidak mudah hitam. Membuat gorengan lebih renyah dan sehat.'
    },
    {
        id: 3,
        name: 'Telur Ayam 1kg',
        price: 28000,
        category: 'Sembako',
        image: 'C:/Users/Admin/.gemini/antigravity/brain/67d00d68-10c7-45d5-82df-78b5ae92d38b/product_eggs_1764037995552.png',
        desc: 'Telur ayam negeri segar langsung dari peternakan. Kaya protein dan nutrisi untuk kebutuhan gizi keluarga.'
    },
    {
        id: 4,
        name: 'Bawang Merah 500g',
        price: 15000,
        category: 'Bumbu',
        image: 'C:/Users/Admin/.gemini/antigravity/brain/67d00d68-10c7-45d5-82df-78b5ae92d38b/product_shallots_1764038022889.png',
        desc: 'Bawang merah Brebes pilihan, ukuran sedang hingga besar. Aroma kuat dan segar, membuat masakan lebih sedap.'
    },
    {
        id: 5,
        name: 'Cabai Rawit 250g',
        price: 12000,
        category: 'Sayur',
        image: 'C:/Users/Admin/.gemini/antigravity/brain/67d00d68-10c7-45d5-82df-78b5ae92d38b/product_chili_1764038048069.png',
        desc: 'Cabai rawit merah super pedas dan segar. Cocok untuk sambal dan bumbu masakan pedas favorit Anda.'
    },
    {
        id: 6,
        name: 'Apel Fuji 1kg',
        price: 45000,
        category: 'Buah',
        image: 'C:/Users/Admin/.gemini/antigravity/brain/67d00d68-10c7-45d5-82df-78b5ae92d38b/product_apple_1764038072721.png',
        desc: 'Apel Fuji segar dengan rasa manis dan tekstur renyah. Kaya vitamin dan serat, camilan sehat untuk keluarga.'
    },
];

// --- State Management ---
let state = {
    cart: JSON.parse(localStorage.getItem('cart')) || [],
    currentView: 'home',
    modalProduct: null,
    modalQty: 1
};

// --- DOM Elements ---
const views = document.querySelectorAll('.view');
const navItems = document.querySelectorAll('.nav-item');
const cartBadge = document.getElementById('cart-badge');
const toast = document.getElementById('toast');

// Modal Elements
const modal = document.getElementById('product-modal');
const modalOverlay = document.querySelector('.modal-overlay');
const modalClose = document.querySelector('.modal-close');
const modalImg = document.getElementById('modal-img');
const modalCategory = document.getElementById('modal-category');
const modalTitle = document.getElementById('modal-title');
const modalPrice = document.getElementById('modal-price');
const modalDesc = document.getElementById('modal-desc');
const modalQtySpan = document.getElementById('modal-qty');
const modalQtyMinus = document.getElementById('modal-qty-minus');
const modalQtyPlus = document.getElementById('modal-qty-plus');
const modalAddBtn = document.getElementById('modal-add-btn');

// --- Router ---
function navigateTo(viewId) {
    // Update View
    views.forEach(view => view.classList.remove('active'));
    document.getElementById(`view-${viewId}`).classList.add('active');

    // Update Nav
    navItems.forEach(item => {
        item.classList.toggle('active', item.dataset.target === viewId);
    });

    state.currentView = viewId;
    window.scrollTo(0, 0);

    // Refresh specific views
    if (viewId === 'cart') renderCart();
}

// --- Render Functions ---
function formatRupiah(number) {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(number);
}

function renderProducts(containerId, products) {
    const container = document.getElementById(containerId);
    container.innerHTML = products.map(product => `
        <div class="product-card" onclick="openModal(${product.id})">
            <img src="${product.image}" alt="${product.name}" class="product-img" loading="lazy">
            <div class="product-info">
                <div class="product-name">${product.name}</div>
                <div class="product-price">${formatRupiah(product.price)}</div>
                <button class="add-to-cart-btn" onclick="event.stopPropagation(); addToCart(${product.id}, 1, event)">
                    + Keranjang
                </button>
            </div>
        </div>
    `).join('');
}

function renderCart() {
    const container = document.getElementById('cart-items');
    const summary = document.getElementById('cart-summary');
    const totalEl = document.getElementById('cart-total');

    if (state.cart.length === 0) {
        container.innerHTML = `
            <div class="empty-state" style="text-align:center; padding: 2rem;">
                <p style="color:var(--text-secondary); margin-bottom:1rem;">Keranjang masih kosong</p>
                <button class="btn-secondary" onclick="navigateTo('catalog')">Mulai Belanja</button>
            </div>
        `;
        summary.classList.add('hidden');
        return;
    }

    summary.classList.remove('hidden');

    let totalPrice = 0;
    container.innerHTML = state.cart.map(item => {
        const product = PRODUCTS.find(p => p.id === item.id);
        totalPrice += product.price * item.qty;
        return `
            <div class="cart-item">
                <img src="${product.image}" class="cart-item-img">
                <div class="cart-item-details">
                    <div class="product-name">${product.name}</div>
                    <div class="product-price">${formatRupiah(product.price)}</div>
                    <div class="cart-controls">
                        <button class="qty-btn" onclick="updateQty(${item.id}, -1)">-</button>
                        <span>${item.qty}</span>
                        <button class="qty-btn" onclick="updateQty(${item.id}, 1)">+</button>
                    </div>
                </div>
            </div>
        `;
    }).join('');

    totalEl.textContent = formatRupiah(totalPrice);
}

// --- Modal Logic ---
function openModal(productId) {
    const product = PRODUCTS.find(p => p.id === productId);
    if (!product) return;

    state.modalProduct = product;
    state.modalQty = 1;

    modalImg.src = product.image;
    modalCategory.textContent = product.category;
    modalTitle.textContent = product.name;
    modalPrice.textContent = formatRupiah(product.price);
    modalDesc.textContent = product.desc;
    modalQtySpan.textContent = state.modalQty;

    modal.classList.remove('hidden');
}

function closeModal() {
    modal.classList.add('hidden');
    state.modalProduct = null;
}

modalOverlay.addEventListener('click', closeModal);
modalClose.addEventListener('click', closeModal);

modalQtyMinus.addEventListener('click', () => {
    if (state.modalQty > 1) {
        state.modalQty--;
        modalQtySpan.textContent = state.modalQty;
    }
});

modalQtyPlus.addEventListener('click', () => {
    state.modalQty++;
    modalQtySpan.textContent = state.modalQty;
});

modalAddBtn.addEventListener('click', (e) => {
    if (state.modalProduct) {
        addToCart(state.modalProduct.id, state.modalQty, e);
        closeModal();
    }
});

// --- Cart Logic & Animation ---
function addToCart(productId, qty = 1, event) {
    const existingItem = state.cart.find(item => item.id === productId);
    if (existingItem) {
        existingItem.qty += qty;
    } else {
        state.cart.push({ id: productId, qty: qty });
    }
    saveCart();
    updateBadge();
    showToast('Item ditambahkan ke keranjang');

    // Animation
    if (event) {
        animateFlyToCart(event.target, productId);
    }
}

function animateFlyToCart(startElement, productId) {
    const product = PRODUCTS.find(p => p.id === productId);
    const cartBtn = document.getElementById('cart-btn');

    if (!startElement || !cartBtn) return;

    const startRect = startElement.getBoundingClientRect();
    const endRect = cartBtn.getBoundingClientRect();

    const img = document.createElement('img');
    img.src = product.image;
    img.classList.add('flying-img');
    img.style.left = `${startRect.left}px`;
    img.style.top = `${startRect.top}px`;

    // Calculate translation
    const tx = endRect.left - startRect.left;
    const ty = endRect.top - startRect.top;

    img.style.setProperty('--tx', `${tx}px`);
    img.style.setProperty('--ty', `${ty}px`);

    document.body.appendChild(img);

    img.addEventListener('animationend', () => {
        img.remove();
        // Shake cart icon
        cartBtn.style.transform = 'scale(1.2)';
        setTimeout(() => cartBtn.style.transform = 'scale(1)', 200);
    });
}

function updateQty(productId, change) {
    const itemIndex = state.cart.findIndex(item => item.id === productId);
    if (itemIndex > -1) {
        state.cart[itemIndex].qty += change;
        if (state.cart[itemIndex].qty <= 0) {
            state.cart.splice(itemIndex, 1);
        }
        saveCart();
        renderCart();
        updateBadge();
    }
}

function saveCart() {
    localStorage.setItem('cart', JSON.stringify(state.cart));
}

function updateBadge() {
    const totalQty = state.cart.reduce((sum, item) => sum + item.qty, 0);
    cartBadge.textContent = totalQty;
    cartBadge.classList.toggle('hidden', totalQty === 0);
}

function showToast(message) {
    toast.textContent = message;
    toast.classList.remove('hidden');
    setTimeout(() => {
        toast.classList.add('hidden');
    }, 2000);
}

// --- Checkout Logic ---
document.getElementById('checkout-btn')?.addEventListener('click', () => {
    if (state.cart.length === 0) return;

    let message = "Halo, saya ingin pesan:\n";
    let total = 0;

    state.cart.forEach(item => {
        const product = PRODUCTS.find(p => p.id === item.id);
        const subtotal = product.price * item.qty;
        total += subtotal;
        message += `- ${product.name} (${item.qty}x) = ${formatRupiah(subtotal)}\n`;
    });

    message += `\nTotal: ${formatRupiah(total)}`;

    // Encode for WhatsApp
    const encodedMessage = encodeURIComponent(message);
    window.open(`https://wa.me/6281234567890?text=${encodedMessage}`, '_blank');
});

// --- Initialization ---
document.addEventListener('DOMContentLoaded', () => {
    // Render Home Products (Featured)
    renderProducts('featured-products', PRODUCTS.slice(0, 4));

    // Render Catalog
    renderProducts('catalog-grid', PRODUCTS);

    // Init Cart Badge
    updateBadge();

    // Nav Listeners
    navItems.forEach(item => {
        item.addEventListener('click', (e) => {
            e.preventDefault();
            const target = item.dataset.target;
            navigateTo(target);
        });
    });

    // Cart Button Header
    document.getElementById('cart-btn').addEventListener('click', () => navigateTo('cart'));

    // Search Filter
    const searchInput = document.getElementById('search-input');
    searchInput?.addEventListener('input', (e) => {
        const keyword = e.target.value.toLowerCase();
        const filtered = PRODUCTS.filter(p => p.name.toLowerCase().includes(keyword));
        renderProducts('catalog-grid', filtered);
    });
});

// Service Worker
if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        navigator.serviceWorker.register('/sw.js');
    });
}
